stages:
    - build-stage
    - deploy-to-stage

build-develop:
   image: europe-north1-docker.pkg.dev/dynamic-net-307721/grandcoin/origin/docker:20.10.18-dind
   services:
    - docker:dind
   stage: build-stage
   script:
    - echo $GITLAB_CICD_KEY | docker login -u _json_key --password-stdin https://$GCP_ARTIFACTORY_PATH
    - docker build -t $GCP_ARTIFACTORY_IMAGE .
    - docker push $GCP_ARTIFACTORY_IMAGE
   only:
    - stage

deploy-to-develop:
  stage: deploy-to-stage
  image: $GCP_IMAGE_TOOLS
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project dynamic-net-307721
    - gcloud container clusters get-credentials grand-cluster-dev --zone europe-north1-a --project dynamic-net-307721
    - kubectl set image -ndevelop deployments/frontend-develop frontend-develop=$GCP_ARTIFACTORY_IMAGE
  only:
    - stage